# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/github-projects-py',
                'doc_host': 'https://larsyencken.github.io',
                'git_url': 'https://github.com/larsyencken/github-projects-py',
                'lib_path': 'ghprojects'},
  'syms': {'ghprojects.core': {'ghprojects.core.foo': ('core.html#foo', 'ghprojects/core.py')}}}