# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/github-projects-py',
                'doc_host': 'https://larsyencken.github.io',
                'git_url': 'https://github.com/larsyencken/github-projects-py',
                'lib_path': 'github_projects_py'},
  'syms': {'github_projects_py.core': {'github_projects_py.core.foo': ('core.html#foo', 'github_projects_py/core.py')}}}